
export const OnlyVaccineInfo = [
    {
        s_no: "3",
        age: ["6"],
        name: 'DTwP',
        gap: '6',
        fullForm: 'Diphtheria Tetanus Pertussis ( w= whole cell )',
        ageOfAdministration: 'Starts at 6 weeks',
        doses: '6wks, 10wks, 14wks, 1.5(1 & 1/2)yr, 5yr(can be replaced by DTaP)',
        noOFDoses: '5(4 if taking DTaP at 5yr)',
        mode: 'IM',
        bodyPart: 'Thigh(Anterolateral Aspect)',
        fever: 'Yes',
        pain: 'Yes',
        disease: 'DTP vaccine can prevent diphtheria, tetanus, and pertussis. All are highly severe diseases with high rates of mortality. Diphtheria and pertussis spread from person to person. Tetanus enters the body through cuts or wounds. DIPHTHERIA (D) can lead to difficulty breathing, heart failure, paralysis, or death. TETANUS (T) causes painful stiffening of the muscles. Tetanus can lead to serious health problems, including being unable to open the mouth, having trouble swallowing and breathing, or death.PERTUSSIS (aP), also known as “whooping cough,” can cause uncontrollable, violent coughing which makes it hard to breathe, eat, or drink. Pertussis can be extremely serious in babies and young children, causing pneumonia, convulsions, brain damage, or death. In teens and adults, it can cause weight loss, loss of bladder control, passing out, and rib fractures from severe coughing',
        effects: 'Besides pain and fever few children may develop seizures or abnormal behaviour, If so then these children to be administered DTaP for the next dose. Soreness or swelling where the shot was given, fever, fussiness, feeling tired, loss of appetite, and vomiting sometimes happen after DTP vaccination. More serious reactions, such as seizures, non-stop crying for 3 hours or more, or high fever (over 105°F) after DTP vaccination happen much less often. Rarely, the vaccine is followed by swelling of the entire arm or leg, especially in older children when they receive their fourth or fifth dose. Very rarely, long-term seizures, coma, lowered consciousness, or permanent brain damage may happen after DTP vaccination.',
        efficacy: '9/10',
        brands: ['Easy five', 'Pentavac', 'Combi 5', 'Quadravac', 'Easy four', 'Easy six'],
        compulsory: 'Yes',
        other: 'Mostly administered as combination vaccine with Hep B and HiB and /or IPV.',
        key: '1'
    },
    {
        name: 'DTaP',
        fullForm: ' Diphtheria Tetanus Pertussis ( a= acellular )',
        ageOfAdministration: 'Starts at 6 weeks',
        doses: '6wks, 10wks, 14wks, 1.5(1 & 1/2)yr, 5yr(can be replaced by DTaP)',
        noOFDoses: '4, if taking DTaP at 5yr',
        mode: 'IM',
        bodyPart: 'Thigh(Anterolateral Aspect)',
        fever: 'No',
        pain: 'No',
        disease: 'DTP vaccine can prevent diphtheria, tetanus, and pertussis. All are highly severe diseases with high rates of mortality. Diphtheria and pertussis spread from person to person. Tetanus enters the body through cuts or wounds. DIPHTHERIA (D) can lead to difficulty breathing, heart failure, paralysis, or death. TETANUS (T) causes painful stiffening of the muscles. Tetanus can lead to serious health problems, including being unable to open the mouth, having trouble swallowing and breathing, or death.PERTUSSIS (aP), also known as “whooping cough,” can cause uncontrollable, violent coughing which makes it hard to breathe, eat, or drink. Pertussis can be extremely serious in babies and young children, causing pneumonia, convulsions, brain damage, or death. In teens and adults, it can cause weight loss, loss of bladder control, passing out, and rib fractures from severe coughing',
        effects: 'low fever, redness, pain, or tenderness where the shot was given, swelling of the entire arm or leg in which the shot was given (may last for up to 7 days), mild fussiness or crying, drowsiness, tiredness or vomiting, loss of appetite',
        efficacy: '9/10',
        brands: ['Infanrix Hexa', 'Pentaxim', 'Hexaxim', 'Infanrix'],
        compulsory: 'Either DTaP or DTwP',
        other: 'Not yet the no 1 recommended choice in India as DTwP (whole cell Pertussis) is whats the choice at mass level. But in view of less pain and less fever preferred at an individual level. Its more expensive than DTwP.',
        key: '6'
    },
    {
        s_no: "24",
        age: ["48"],
        gap: "12",
        name: 'Hep A',
        fullForm: 'Hepatitis A Vaccine',
        ageOfAdministration: 'Starts at 12 months to 23 months. Unvaccinated older children and adults can also take the Vaccine.',
        doses: 'Doses given at 12 months upto 23 months with 2nd dose six months after the first.',
        noOFDoses: '2 (Maybe a single dose in a few brands)',
        mode: 'SC/IM  (Intramuscular)',
        bodyPart: 'Depends on the brand',
        fever: 'No',
        pain: 'No',
        disease: 'Hepatitis A vaccine can prevent hepatitis A. Hepatitis A is a serious liver disease. It is usually spread through close personal contact with an infected person or when a person unknowingly ingests the virus from objects, food, or drinks that are contaminated by small amounts of stool from an infected person.',
        effects: 'High fever, Pale skin, Weakness or dizziness, A fast heart beat',
        efficacy: '9/10',
        brands: ['Biovac A (wochhardt)', 'Avaxim (sanofi)', 'Havrix 720 (GSK)'],
        compulsory: 'Yes',
        other: 'If a child who has not received the vaccine and develops Hepatitis(due to HEP A virus), then that child does not need to get this vaccine',
        key: '7'
    },
    {
        s_no: "6",
        age: ["6"],
        name: 'Hib',
        gap: '6',
        fullForm: 'H influenzae B vaccine',
        ageOfAdministration: 'Recommended at 6 weeks, 10 weeks 14 weeks and 1 1/2 years ( booster ) ',
        doses: '',
        noOFDoses: '4',
        mode: 'IM',
        bodyPart: 'Thigh(Anterolateral Aspect)',
        fever: 'No',
        pain: 'No',
        disease: 'Haemophilus influenza is a pleomorphic gram-negative coccobacillus which exists in encapsulated and non-encapsulated forms. The encapsulated organisms, also called the typeable H. influenzae are classified from a to f,based on distinct capsular polysaccharide. The non-encapsulated forms are known as nontypeable strains.',
        effects: 'Anaphylaxis maybe',
        efficacy: '9/10',
        brands: ['Easy five', 'Pentavac', 'Combie 5', 'Quadravac', 'Easy four', 'Easy six', 'Hexaxim', 'pentaxim'],
        compulsory: 'Yes',
        other: 'Not given these days as Individual vaccine',
        key: '8'
    },
    
    {
        s_no: "2",
        age: ["0"],
        name: 'HepB',
        gap: '0',
        fullForm: 'Hepatitis B',
        ageOfAdministration: 'Recommended at 6 weeks, 10 weeks 14 weeks (this dose is additional and is beneficial when given with combination vaccine)',
        doses: '',
        noOFDoses: '3',
        mode: 'IM',
        bodyPart: 'Thigh(Anterolateral Aspect)',
        fever: 'No',
        pain: 'No',
        disease: 'Hepatitis B is a virus which causes liver damage It is a permanent infection and eventually leads to liver failure and death. Spreads through Contaminated needles ,instruments, Blood transfusion Mother to child transmission in case of a baby born to an infected mother.',
        effects: 'Anaphylaxis after previous dose, soreness, malaise',
        efficacy: '9/10',
        brands: ['Genevac (sii)', 'Bevac', 'Revac'],
        compulsory: 'Yes',
        other: 'Mother to child transmission is preventable with timely Vaccination of child with vaccine along with hepatitis B immunoglobulin',
        key: '12'
    },
    
    {
        s_no: "22",
        age: ["36"],
        name: 'MMR',
        gap: '12',
        fullForm: 'Measles Mumps and Rubella vaccine',
        ageOfAdministration: '9 months, 15 months, Booster(3rd) dose at 5 years of age',
        doses: '6wks, 10wks, 14wks',
        noOFDoses: '2',
        mode: 'subcutaneous route',
        bodyPart: 'front of arm, Also can be in the back of thigh',
        fever: 'No',
        pain: 'No',
        disease: 'The MMR vaccine is very effective at protecting people against measles, mumps, and rubella, and preventing the complications caused by these diseases. People who receive MMR vaccination according to the U.S. vaccination schedule are usually considered protected for life against measles and rubella.',
        effects: 'Sore arm from the shot, Fever, Mild rash',
        efficacy: '9/10',
        brands: ['Tresivac', 'Priorix'],
        compulsory: 'Optional',
        other: 'It is a live attenuated vaccine, Can be given in combination of chicken pox vaccine. The vaccine is contraindicated in those with a severe history of allergic reactions to the constituents of the vaccine that domicile.',
        key: '16'
    },

    {
        name: 'Rabies',
        fullForm: 'Rabies',
        ageOfAdministration: 'No fixed age',
        doses: 'GIVEN AFTER DOG BITE AND NOT ROUTINELY',
        noOFDoses: '5',
        mode: 'INTRAMUSCULAR',
        bodyPart: ': ANTEROLATERAL THIGH OLDER CHILDREN AND ADULTS CAN BE GIVEN IN THE DELTOID REGION',
        fever: 'No',
        pain: 'No',
        disease: 'RABIES IS A SLOW VIRUS DISEEASE SPREAD VIA DOG BITES (MOST COMMON) ',
        effects: 'None',
        efficacy: '9/10',
        brands: ['Tresivac (SII)', 'RABIVAX (SII)', 'CHIRORAB(BBIL)', 'BERAB(BE)', 'VAXIRAB(ZYDUS)', 'ABHAYRAB'],
        compulsory: 'OptiCOMPULSORY AFTEWR A DOG BITEonal',
        other: 'It is THE ONLY VACCINE WHICH GIVEN POST EXPOSURE',
        key: '18'
    },
    {
        s_no: "4",
        age: ["6"],
        name: 'IPV',
        gap: '6',
        fullForm: 'Inactivated polio vaccine',
        ageOfAdministration: '6 weeks ( 1 ½ months ), 10 weeks ( 2 ½ months ), 14 weeks ( 3 ½ months ), Booster dose at 1 ½ years of age (18months )',
        doses: '',
        noOFDoses: '4 ',
        mode: 'IM',
        bodyPart: 'Anterolateral thigh',
        fever: 'No',
        pain: 'No',
        disease: 'Polio is a debilitating disease caused by the poliomyelitis virus. Once infected polio is non treatable. Polio has been eradicated from the world and the last country to become polio free was India and that happened in 2012. This has been possible through intense immunization programs and a high rate of vaccination shall keep it that way.',
        effects: 'Mild redness/soreness/fever at the site of injection.',
        efficacy: '9/10',
        brands: ['Poliovac (SII)', 'Easy six (sanofi)', 'Pentaxim', 'Hexaxim', 'Infanrix hexa', 'Tetraxim'],
        compulsory: 'Yes',
        other: 'Its always better to take IPV over OPV as IPV is a inactivated vaccine where the virus is dead. Since India has been declared polio free since 2012, therefore, all patients taking OPV are recommended at least one dose of IPV.',
        key: '19'
    },
    
    {
        s_no: "37",
        age: ["480"],
        name: 'HPV',
        gap: '288',
        fullForm: 'Human Papilloma Virus',
        ageOfAdministration: '10 years to 12 years',
        doses: '2 doses over a six-month time frame (3 if the first dose is after 14 years of age).',
        noOFDoses: '2 doses between 9 to 14 years, 6 months apart,In children above 14 years three doses to be given ',
        mode: 'IM',
        bodyPart: 'deltoid region of the upper arm /anterolateral thigh',
        fever: 'No',
        pain: 'No',
        disease: 'About 80% of the population gets infected with HPV. HPV infection is an essential factor in cervical carcinogenesis and cervical carcinoma is the second most common cause of cancer among women worldwide. Other malignancies in both men and women such as esophageal, penile, vulvar, vaginal cancer, and anal cancer have been casually associated with the virus. The low risk HPV types 6 and 11 are responsible for about 90% of anogenital warts and almost all recurrent respiratory papillomatosis. Cancer is the most serious possible complication from HPV infection.',
        effects: 'None',
        efficacy: '9/10',
        brands: ['Gardasil', 'Cervarix (GSK)'],
        compulsory: 'No',
        other: 'They are all minor adverse effects and no serious vaccine-related adverse events have been reported either in trial. Human Papillomavirus vaccines should not be given to anyone who has experienced a severe allergic reaction after a previous HPV vaccine dose, or to a component of the vaccine',
        key: '23'
    },
    {
        name: 'MCV',
        fullForm: 'Meningococcal Conjugate Vaccine',
        ageOfAdministration: '9 months through 23 months of age, given astwo dose series 3 months apart.',
        doses: '',
        noOFDoses: '2',
        mode: 'INTRAMUSCULAR',
        bodyPart: ': ANTEROLATERAL THIGH',
        fever: 'Yes',
        pain: 'Mild fever',
        disease: 'Meningococcal disease is caused by gram-negative diplococcus bacterianeisseria meningitidis. Humans are only reservoir for meningococcal bacteria. It can present as acute illness and rarely chronic illness. Meningococcus can cause meningitis, septicemia, pneumonia, myocarditis, pericarditis, arthritis, and conjunctivitis.',
        effects: 'Mild Soreness, redness, or swelling where the shot was given',
        efficacy: '9/10',
        brands: ['Menectra', 'Menveo'],
        compulsory: 'Yes',
        other: 'Usually , disease occurs in the dry season in endemic areas. It can present as acute illness and rarely chronic illness.',
        key: '24'
    },
    {
        s_no: "8",
        age: ["6"],
        name: 'PCV',
        gap: '6',
        fullForm: 'Pneumococcal Conjugate Vaccine (also commonly called pneumonia vaccine)',
        ageOfAdministration: '6 weeks, 8 weeks, 10 weeks, booster at 15 or 18 months of age.',
        doses: '',
        noOFDoses: '4',
        mode: 'INTRAMUSCULAR',
        bodyPart: 'ANTEROLATERAL THIGH',
        fever: 'No',
        pain: 'No',
        disease: 'Pneumococcal pneumonia and meningitis. Vaccines help prevent pneumococcal disease, which is any type of illness caused by Streptococcus pneumoniae (Pneumococcus) bacteria. Spectrum of pneumococcal disease (PD) ranges from: Asymptomatic nasopharyngeal carriage, Non Invasive diseases are due to contagious spread and include otitis media, sinusitis, and pneumonia ; and invasive disease (hematogenous spread) - invasive pneumococcal disease, invasive pneumococcal disease (IPD) (septicemia), meningitis, pneumonia, others like soft tissue infections, osteomyelitis, and endocarditis.',
        effects: 'Mild redness/ fever/ soreness at site of injection (in less than 10%).The safety of PCV has been well studied and all formulations are considered to have an excellent safety profile.',
        efficacy: '9/10',
        brands: ['Synflorix(GSK)', 'Prevenar 13(pfizer)', 'Pneumosil (sii)'],
        compulsory: 'Yes',
        other: 'Pneumococcal disease will not occur without preceding nasopharyngeal colonization with the homologous strain. Pneumococcal carriage is believed to be an important source of horizontal spread of this pathogen within the community. Brand interchangeability is usually not recommended.',
        key: '25'
    },
    
    {
        s_no: "26",
        age: ["60"],
        name: 'Varicella',
        gap: '12',
        fullForm: 'Chicken pox vaccine',
        ageOfAdministration: '15 months, booster at 5 yrs of age',
        doses: '2',
        noOFDoses: 'second dose can also be given six months after the first dose',
        mode: 'INTRAMUSCULAR',
        bodyPart: 'Front of arm(forearm), Can also be given in the back of thigh.',
        fever: 'No',
        pain: 'No',
        disease: 'The chickenpox vaccine protects children and adults from chickenpox. Varicella is caused by the very highly contagious varicella-zoster virus(VZV) which has a world wide distribution. Varicella spreads through inhalation of droplet nuclei and less commonly through contact with contaminated surfaces/lesions of the infected. It is highly communicable. The disease is usually benign can be severe in neonates, pregnant women, and adults.',
        effects: 'Well tolerated and the side effects reported are mild and transient',
        efficacy: '9/10',
        brands: ['Varilrix(GSK)', 'Variped(MSD)', 'Nexipox(novo)', 'Biovac V', 'Varivax', 'Zuvicella'],
        compulsory: 'Yes',
        other: 'An unvaccinated child who has had chicken pox .. develops immunity and hence this Vaccine is not recommended for them Being a live attenuated Vaccine ,for Vaccination of lowered immunity individuals its to be avoided or taken only after due consultation with your healthcare provider These being 1. HIV 2. Those suffering from cancer 3. Those on steroids',
        key: '28'
    },
    
    {
        s_no: "7",
        age: ["6"],
        name: 'Rotavirus',
        gap: '6',
        fullForm: 'Rotavirus',
        ageOfAdministration: '6 wks, 10 wks, 14 wks.',
        doses: 'First dose to be give maximum by 16 wks, And last dose can be delayed upto max 32 wks',
        noOFDoses: '3',
        mode: 'oral',
        bodyPart: 'oral',
        fever: 'No',
        pain: 'No',
        disease: 'Rotavirus vaccine is a vaccine used to protect against rotavirus infections, which are the leading cause of severe diarrhea among young children. Rotavirus spreads easily among infants and young children. The virus can cause severe watery diarrhea, vomiting, fever, and abdominal pain. Children who get rotavirus disease can become dehydrated and may need to be hospitalized. Good hygiene like hand washing and cleanliness are important, but are not enough to control the spread of the disease. Rotavirus vaccine is the best way to protect your child against rotavirus disease. In summary : vaccine protects against diarrhea',
        effects: 'None',
        efficacy: '9/10',
        brands: ['Rotasure', 'Rotavaq', 'RotaTeq', 'Rotasil', 'Rotashield'],
        compulsory: 'Yes',
        other: 'Dosing may vary according to brand Rotateq is only two doses Rest all are 3 doses (No booster recommended)',
        key: '31'
    },
    
    {
        s_no: "0",
        age: ["0"],
        name: 'BCG',
        gap: '0',
        fullForm: 'Bacillus camellte Gurien vaccine',
        ageOfAdministration: 'Should be given soon after birth or try to give within two weeks of birth (so that there is a gap of 4 weeks between BCG and the 6 week vaccines) If not received can be given anytime before 6 months of age.',
        doses: '',
        noOFDoses: '1',
        mode: 'ID intradermal',
        bodyPart: 'left shoulder',
        fever: 'No',
        pain: 'No',
        disease: 'Tuberculosis, Very weak protection but India being an endemic country its mandatory to take the vaccine ',
        effects: 'In rare cases may lead to anaphylaxis. Most common is pustule formation at the site of Vaccination which heals on its own leaving the typical BCG scar. Rarely may lead to inflammation in adjacent lymph nodes, but upon biopsy they are generally revealed to be sterile',
        efficacy: '9/10',
        brands: ['Tubervac'],
        compulsory: 'Yes',
        other: 'Its is a live attenuated vaccine. Post Vaccination there is inflammation at the site of Vaccination which leave the characteristic scar after about three months',
        key: '34'
    },
    {
        s_no: "1",
        age: ["0"],
        name: 'OPV',
        gap: '0',
        fullForm: 'Oral polio vaccine',
        ageOfAdministration: 'Recommended at birth, 10 weeks and 6 months (only if not taking IPV). OPV is being phased out in India.',
        doses: '',
        noOFDoses: '3',
        mode: 'Oral vaccine',
        bodyPart: 'Oral route',
        fever: 'No',
        pain: 'No',
        disease: 'Polio is a debilitating disease caused by the poliomyelitis virus. Once infected polio is non treatable. Polio has been eradicated from the world and the last country to become polio free was India and that happened in 2012. This has been possible through intense immunization programs and a high rate of vaccination shall keep it that way.',
        effects: 'OPV is associated with Vaccine Associated Paralytic Polio (VAPP) in approximately one in 2.7 million doses of OPV. It can occur in the recipient of OPV or can occur in a close unvaccinated or non immune contact of the vaccine recipient who is excreting the virus.',
        efficacy: '9/10',
        brands: ['Bio polio'],
        compulsory: 'compulsory only if not taken IPV',
        other: 'Oral polio vaccine is slowly being phased out in India. Presently , in India, OPV 0 is advised even with an all IPV schedule. Pulse polio vaccination is over and above routine polio vaccination.',
        key: '35'
    },
    
    {
        s_no: "23",
        age: ["40"],
        name: 'TCV',
        gap: '12',
        fullForm: 'Typhoid conjugate vaccine',
        ageOfAdministration: 'Recommended at 6 months to 9 months of age',
        doses: 'Second dose maybe at 2 years age',
        noOFDoses: '1 dose(maybe 2 doses)',
        mode: 'IM intramuscular',
        bodyPart: 'anterolateral aspect of thigh',
        fever: 'No',
        pain: 'No',
        disease: 'Typhoid or enteric fever is caused by salmonella typhi. Salmonella Typhi (S. Typhi) are bacteria that infect the intestinal tract and the blood. The disease is referred to as typhoid fever. S. Paratyphi bacteria cause a similar, but milder illness, which comes under the same title Its spread via the faeco oral route, i.e., unclean water ,not washing hands after defecation ,drinking water mixed with sewage etc Conjugate vaccines have shown to provide good protection against this disease.',
        effects: 'Occasional fever / soreness / redness at site of injection',
        efficacy: '9/10',
        brands: ['Enteroshield', 'Typhbar TCV', 'Zyvac TCV', 'Typhivac BE'],
        compulsory: 'yes',
        other: 'Though now there are claims of just one dose being enough, still there are groups which believe that two doses are required for better Immunity. If a child has suffered from typhoid disease, culture proven we need to give the typhoid injection after complete recovery from the illness.',
        key: '39'
    },
    {
        s_no: "36",
        age: ["480"],
        name: 'TDaP',
        gap: '288',
        fullForm: 'Combined tetanus, diphtheria and acellular pertussis',
        ageOfAdministration: '11years-12 years of age.',
        doses: '',
        noOFDoses: '1 dose',
        mode: 'IM intramuscular',
        bodyPart: 'anterolateral aspect of thigh',
        fever: 'Yes',
        pain: 'Yes',
        disease: 'Tdap vaccine can prevent tetanus, diphtheria, and pertussis. Diphtheria and pertussis spread from person to person. Tetanus enters the body through cuts or wounds.',
        effects: 'Pain, redness, or swelling in the arm where the shot was given',
        efficacy: '9/10',
        brands: ['Boostrix(GSK)', 'ADACEL(Sanofi)'],
        compulsory: 'yes',
        other: 'Tdap is a booster immunization given at age 11 that offers continued protection from those diseases for adolescents and adults.',
        key: '41'
    },
    {
        s_no: "36",
        age: ["480"],
        name: 'Influenza',
        gap: '288',
        fullForm: 'Influenza Vaccine',
        ageOfAdministration: '6 months and 7 months',
        doses: '',
        noOFDoses: '2 for the first time and subsequently one dose every year.',
        mode: 'IM intramuscular',
        bodyPart: 'anterolateral aspect of thigh',
        fever: 'No',
        pain: 'No',
        disease: 'Influenza vaccines, also known as flu shots or flu jabs, are vaccines that protect against infection by influenza viruses. New versions of the vaccines are developed twice a year, as the influenza virus rapidly changes. Generally influenza causes common cough and cold but can lead to serious disease with complications such as pneumonia, otitis media and rarely ARDS and death. Other complications include encephalitis, myocarditis, multi organ failure and sepsis.',
        effects: 'Mild Soreness/ redness/ swelling where shot is given',
        efficacy: '9/10',
        brands: ['Influvac tetra', 'Variflu', 'Fluarix tetra'],
        compulsory: 'No',
        other: 'Is a respiratory infection caused by influenza virus. All children over 6 months old should get a flu shot each year.',
        key: '42'
    },
    
    {
        s_no: "36",
        age: ["480"],
        name: 'Yellow Fever Vaccine',
        gap: '288',
        fullForm: 'Yellow Fever Vaccine',
        ageOfAdministration: '6–8 months (should be vaccinated only if they must travel to areas of ongoing epidemic yellow fever)',
        doses: '',
        noOFDoses: '1',
        mode: 'Subcutaneous administration',
        bodyPart: '',
        fever: 'No',
        pain: 'No',
        disease: 'Yellow fever vaccine is a vaccine that protects against yellow fever. Yellow fever is a viral infection that occurs in Africa and South America. Most people begin to develop immunity within ten days of vaccination and 99 percent are protected within one month, and this appears to be lifelong.',
        effects: 'Injection site reactions (redness, pain, swelling, tenderness, soreness, aches, or a lump)',
        efficacy: '9/10',
        brands: [],
        compulsory: 'No',
        other: 'Currently only given at government setup. The ‘yellow’ in the name refers to the jaundice that affects some patients. Carries from one person to other.',
        key: '45'
    },
    {
        s_no: "36",
        age: ["480"],
        name: 'JE Vaccine',
        gap: '288',
        fullForm: 'Japanese encephalitis Vaccine',
        ageOfAdministration: 'Recommended at one year of age and second dose after 4 weeks of the first dose.',
        doses: '',
        noOFDoses: '2',
        mode: 'IM (intramuscular)',
        bodyPart: 'anterolateral aspect of the thigh',
        fever: 'Yes',
        pain: 'Yes',
        disease: 'Japanese encephalitis is a neurological disease mainly affecting the central nervous system (CNS). JE is caused by Japanese encephalitis virus which is a flavivirus belonging to the family of flaviviridae, which is transmitted to humans by mosquito bites mainly by Culex tritaeniorhynchus types of mosquitoes.',
        effects: 'Mild soreness/fever/ redness at the site of injection.',
        efficacy: '9/10',
        brands: ['Jenvac', 'JE shield'],
        compulsory: 'No',
        other: 'The JE vaccine (brands) can be administered interchangeably. IAP mentions that the need for boosters is uncertain',
        key: '46'
    },
]

export default {
    OnlyVaccineInfo,
}
