
    export const vaccineInfo  = [
        {
            name: 'DwPT',
            fullForm: 'Diphtheria Tetanus Pertussis ( w= whole cell )',
            ageOfAdministration: 'Starts at 6 weeks',
            doses: '6wks, 10wks, 14wks, 1.5(1 & 1/2)yr, 5yr(can be replaced by DTaP)',
            noOFDoses: '4 if taking DTaP at 5yr',
            mode: 'IM',
            bodyPart: 'Thigh(Anterolateral Aspect)',
            fever: 'Yes',
            pain: 'Yes',
            disease: 'DTP vaccine can prevent diphtheria, tetanus, and pertussis.',
            effects: 'Besides pain and fever few children main develop seizures or abnormal behaviour, If so then these children to be administered DTaP for the next dose.',
            efficacy: '9/10',
            brands: ['Easy five','Pentavac','Combie 5','Quadravac','Easy four','Easy six'],
            compulsory: 'Yes',
            other: 'Mostly administered as combination vaccine with Hep B and HiB and /or IPV.',
            key: '1'
        },
        {
            name: 'Dtap',
            fullForm: ' Diphtheria Tetanus Pertussis ( a= acellular )',
            ageOfAdministration: 'Starts at 6 weeks',
            doses: '6wks, 10wks, 14wks, 1.5(1 & 1/2)yr, 5yr(can be replaced by DTaP)',
            noOFDoses: '4 if taking DTaP at 5yr',
            mode: 'IM',
            bodyPart: 'Thigh(Anterolateral Aspect)',
            fever: 'Yes',
            pain: 'Yes',
            disease: '',
            effects: 'Besides pain and fever few children main develop seizures or abnormal behaviour, If so then these children to be administered DTaP for the next dose.',
            efficacy: '9/10',
            brands: ['Easy five','Pentavac','Combie 5','Quadravac','Easy four','Easy six'],
            compulsory: 'Yes',
            other: 'Mostly administered as combination vaccine with Hep B and HiB and /or IPV.',
            key: '2'
        },
        {
            name: 'Hep A',
            fullForm: 'Hepatitis A Vaccine',
            ageOfAdministration: 'Starts at 12 months to 23 months. Unvaccinated older children and adults can also take the Vaccine.',
            doses: '12 months upto 23 months with 2nd dose six months after the first.',
            noOFDoses: '2(Maybe a single dose in a few brands)',
            mode: 'SC/IM',
            bodyPart: 'Depends on the brand',
            fever: 'No',
            pain: 'No',
            disease: 'polio',
            effects: 'Besides pain and fever few children main develop seizures or abnormal behaviour, If so then these children to be administered DTaP for the next dose.',
            efficacy: '9/10',
            brands: 'Bio vac A (wochhardt), Avaxim (sanofi), Havrix 720 (GSK) ',
            compulsory: 'Yes',
            other: 'Mostly administered as combination vaccine with Hep B and HiB and /or IPV.',
            key: '3'
        },
        {
            name: 'Hib',
            fullForm: 'H influenza B',
            ageOfAdministration: 'Recommended at 6 weeks, 10 weeks 14 weeks and 1 1/2 years ( booster ) ',
            doses: '6wks, 10wks, 14wks, 1.5(1 & 1/2)yr, 5yr(can be replaced by DTaP)',
            noOFDoses: '4',
            mode: 'IM',
            bodyPart: 'Thigh(Anterolateral Aspect)',
            fever: 'No',
            pain: 'No',
            disease: 'Hib is known to cause sever form of meningitis ',
            effects: 'Anaphylaxis maybe ',
            efficacy: '9/10',
            brands: ['Easy five','Pentavac','Combie 5','Quadravac','Easy four','Easy six','Hrexaxim','pentaxim'],
            compulsory: 'Yes',
            other: 'Not given these days as Individual vaccine',
            key: '4'
        },
        {
            name: 'HepB',
            fullForm: 'Hepatitis B',
            ageOfAdministration: 'Recommended at 6 weeks, 10 weeks 14 weeks and 1 1/2 years ( booster ) ',
            doses: '6wks, 10wks, 14wks',
            noOFDoses: '3',
            mode: 'IM',
            bodyPart: 'Thigh(Anterolateral Aspect)',
            fever: 'No',
            pain: 'No',
            disease: 'Hepatitis B is a virus which causes liver damage It is a permanent infection and eventually leads to liver failure and death ',
            effects: 'Anaphylaxis after previous dose, soreness, malaise',
            efficacy: '9/10',
            brands: ['Hep B (sii)'],
            compulsory: 'Yes',
            other: 'Mother to child transmission is preventable with timely Vaccination of child with vaccine along with hepatitis B immunoglobulin',
            key: '5'
        },
        {
            name: 'Cholera',
            fullForm: 'Cholera',
            ageOfAdministration: 'Recommended at birth, 10 weeks, 6 Months',
            doses: '6wks, 10wks, 14wks',
            noOFDoses: '3',
            mode: 'Oral vaccine ',
            bodyPart: 'Oral vaccine ',
            fever: 'No',
            pain: 'No',
            disease: 'Prevent s against Cholera,Causes severe watery diarrhea ',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Bio Polio'],
            compulsory: 'Optional',
            other: 'Not routinely given',
            key: '6'
        },
        {
            name: 'MMR',
            fullForm: 'Measles Mumps and Rubella vaccine',
            ageOfAdministration: '9 months, 15 months, Booster dose at 5 years of age',
            doses: '6wks, 10wks, 14wks',
            noOFDoses: '3',
            mode: 'subcutaneous',
            bodyPart: 'front of arm, Also can be in the back of thigh',
            fever: 'No',
            pain: 'No',
            disease: 'Prevent s againstMeasles, Mumps, And rubella ',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Tresivac (SII)'],
            compulsory: 'Optional',
            other: 'It is a live attenuated vaccine, Can be given in combination of choicken pox vaccine',
            key: '7'
        },
        {
            name: 'Rabies',
            fullForm: 'Rabies',
            ageOfAdministration: 'No fixed age',
            doses: 'GIVEN AFTER DOG BITE AND NOT ROUTINELY',
            noOFDoses: '5',
            mode: 'INTRAMUSCULAR',
            bodyPart: ': ANTEROLATERAL THIGH OLDER CHILDREN AND ADULTS CAN BE GIVEN IN THE DELTOID REGION',
            fever: 'No',
            pain: 'No',
            disease: 'RABIES IS A SLOW VIRUS DISEEASE SPREAD VIA DOG BITES (MOST COMMON) ',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Tresivac (SII)','RABIVAX (SII)','CHIRORAB(BBIL)','BERAB(BE)','VAXIRAB(ZYDUS)','ABHAYRAB'],
            compulsory: 'OptiCOMPULSORY AFTEWR A DOG BITEonal',
            other: 'It is THE ONLY VACCINE WHICH GIVEN POST EXPOSURE',
            key: '8'
        },
        {
            name: 'IPV',
            fullForm: 'Inactivated polio vaccine',
            ageOfAdministration: '6 weeks ( 1 ½ months ), 10 weeks ( 2 ½ months ), 14 weeks ( 3 ½ months ), Booster dose at 1 ½ years of age (18months )',
            doses: 'If not taken / given then atleast one dose of IPV at 3 ½ months or 1 ½ years of age  ',
            noOFDoses: '4 ',
            mode: 'INTRAMUSCULAR',
            bodyPart: 'ANTEROLATERAL THIGH',
            fever: 'No',
            pain: 'No',
            disease: ' Polio, or poliomyelitis, is a crippling and potentially deadly disease. It is caused by the poliovirus. The virus spreads from person to person and can invade an infected person’s brain and spinal cord, causing paralysis (can’t move parts of the body).',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Poliovac (SII)','Easy six (sanofi)','Pentaxim','Hexaxim','Infanrix hexa','Tetraxim'],
            compulsory: 'Yes',
            other: 'Its always better to take IPV over OPV as IPV is a inactivated vaccine where the virus is dead',
            key: '9'
        },
        {
            name: 'HPV',
            fullForm: 'Human Papilloma Virus',
            ageOfAdministration: '9 years to 14 years',
            doses: 'Currently recommended for all females upto 45 years of age',
            noOFDoses: '2 doses between 9 to 14 years, 6 months apart,In children above 14 years three doses to be given ',
            mode: 'INTRAMUSCULAR',
            bodyPart: ': ANTEROLATERAL THIGH',
            fever: 'No',
            pain: 'No',
            disease: 'Cervical cancer in women is the second most common after breast cancer, This is the only vaccine which has proven to prevent against cervical cancer in women',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Gardasil','Cervarix (GSK)'],
            compulsory: 'Yes',
            other: 'Its always better to take IPV over OPV as IPV is a inactivated vaccine where the virus is dead',
            key: '10'
        },
        {
            name: 'MCV',
            fullForm: 'Meningococcal Conjugate Vaccine',
            ageOfAdministration: 'Above 2 years of age',
            doses: '1',
            noOFDoses: '2 doses between 9 to 14 years, 6 months apart,In children above 14 years three doses to be given ',
            mode: 'INTRAMUSCULAR',
            bodyPart: ': ANTEROLATERAL THIGH',
            fever: 'No',
            pain: 'No',
            disease: 'Nisseria meningitidis is a bacteria that causes fulminant sepsis and severe meningitis in children.This vaccine prevents against that',
            effects: 'None',
            efficacy: '9/10',
            brands: ['Menectra','Menveo (GSK)'],
            compulsory: 'Yes',
            other: 'None',
            key: '11'
        },
      ]
      
      export default {
          vaccineInfo,
      }
